### ISSUE TITLE
XTM 1.0 importer: Wrong handling of xml:base

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ontopia/ontopia#112]
```
<topicMap xml:base="http://www.example.org/foo.xtm">
   <topic id="bar"/>
<topicMap>

CXTM:
<topicMap>
<topic number="1">
<itemIdentifiers>
<locator>http://www.example.org/foo.xtm#bar</locator>
</itemIdentifiers>
</topic>
<topicMap>

Ontopia's output:
<topicMap>
<topic number="1">
<itemIdentifiers>
<locator>#bar</locator>
</itemIdentifiers>
</topic>
<topicMap>

See also: <http://www.infoloom.com/pipermail/topicmapmail/2009q3/007907.html>
```

Original issue reported on code.google.com by `lars.he...@gmail.com` on 11 Aug 2009 at 2:02

**Comment by qsiebers** [comment]
Linking original reporter: @heuer

**Comment by qsiebers** [comment]
The relevant code is in [XTMContentHandler.java:1188](https://github.com/ontopia/ontopia/blob/7ba6575090409f268d15c9b03e2d35102410bc2d/ontopia-engine/src/main/java/net/ontopia/topicmaps/xml/XTMContentHandler.java#L1188):
```java
return doc_address.resolveAbsolute(address);
```

I've had a go at changing it to the base stack, just like on line 1190, but this causes 25 test failures. This lead me to the following test case files:
- [xmlbase-problem.xtm](https://github.com/ontopia/ontopia/blob/master/ontopia-engine/src/test/resources/net/ontopia/testdata/canonical/in/xmlbase-problem.xtm)
- [xmlbase-problem2.xtm](https://github.com/ontopia/ontopia/blob/master/ontopia-engine/src/test/resources/net/ontopia/testdata/canonical/in/xmlbase-problem2.xtm)

These actually assert that the Ontopia behaviour is valid. 

I've also had a quick look at the RFC's mentioned here and in code, and they do seem to be contradicting each other. 

I think the solution is to be pragmatic and leave the Ontopia implementation as is. I also consider XTM 1 to be deprecated by XTM 2.
