### ISSUE TITLE
publish tologUpdate through tmrap over soap

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ontopia/ontopia#314]
```
The tologUpdate method in TMRAP was not yet visible.
I added tologUpdate to the wsdl, and have attached also the implementation as 
axis service file.

```

Original issue reported on code.google.com by `jelle.pe...@gmail.com` on 11 Oct 2010 at 10:42

Attachments:
- [TMRAPService.wsdl](https://storage.googleapis.com/google-code-attachments/ontopia/issue-314/comment-0/TMRAPService.wsdl)
- [TMRAPService.aar](https://storage.googleapis.com/google-code-attachments/ontopia/issue-314/comment-0/TMRAPService.aar)

**Comment by qsiebers** [comment]
Duplicate of #365
