### ISSUE TITLE
Use Findbugs in build process

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ontopia/ontopia#45]
```
Benjamin Bock has suggested to use Findbugs during development.

Maybe it would make sense to integrate Findbugs in the building process.

Findbugs: http://findbugs.sourceforge.net/
```

Original issue reported on code.google.com by `lars.he...@gmail.com` on 30 Jun 2009 at 5:52

**Comment by qsiebers** [comment]
These kinds of checks are now available at [Codacy](https://www.codacy.com/app/Ontopia/ontopia)
