### ISSUE TITLE
Outdated docs published on ontopia.net

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ontopia/ontopia#498]
```
<http://www.ontopia.net/omnigator/docs/query/predicate-reference.html>

Missing:
* datatype predicate
* coalesce 

Maybe more. 

The current download contains up to date docs. 

Would be nice if the docs published at ontopia.net would mirror the current 
Ontopia release.
```

Original issue reported on code.google.com by `lars.he...@gmail.com` on 16 Jul 2014 at 9:16

**Comment by qsiebers** [comment]
The ontopia.net has moved to a new server, making it easier to maintain. A new omnigator version has been added to this server, bringing the omnigator docs up to date.
