### ISSUE TITLE
ClassInstanceIndex implementations differ

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ontopia/ontopia#510]
```
For example getTopics(TopicIF):

- Basic implementation does returns an empty set for a null type
- RDBMS implementation returns *all* topics for a null type

I'm not sure which of these are correct.
```

Original issue reported on code.google.com by `qsieb...@gmail.com` on 13 Oct 2014 at 8:21

**Comment by qsiebers** [comment]
> I'm in favor of letting Occurrence, Association and Role queries throw NPE's if 
> the provided type is null.

This would be to aggressive as methods depending on ClassInstanceIndexIF do not handle NPE's but can deal with empty collections just fine. So empty collections is the way to go
