### ISSUE TITLE
Ontopia on Github?

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ontopia/ontopia#513]
```
Google code is going to be shut down.
Is there a copy repo on Github?
```

Original issue reported on code.google.com by `leiyu.cpp` on 13 Mar 2015 at 7:10

**Comment by qsiebers** [comment]
The actual move has been completed. Google code now has a redirect to this github location.

**Comment by qsiebers** [comment]
More then a month has passed, some minor bugs regarding the move have been reported and fixed.
