### ISSUE TITLE
Ontopia should upgrade to Java 8

### ISSUE THREAD

**Issue by qsiebers** [ontopia/ontopia#523]
As of April 2015, public updates for java 7 have ended. To ensure continued support and security in Ontopia, we should upgrade to java 8.

**Comment by qsiebers** [comment]
I've created a branch (https://github.com/ontopia/ontopia/commits/java8) for changed needed for java 8, and testing.

**Comment by achea** [comment]
Hello,

I'm trying to give the source a go and while I can get it to compile, I am hitting some roadblocks when running it, one of which are HTTP 500 errors I get from Omnigator when I try to navigate to certain things, e.g. "Customize" or "Filter".

Here is the apache tomcat logs:  https://gist.github.com/achea/f67f5457eec15cc61fc22af4f361ea5a

A SO answer (https://stackoverflow.com/questions/24301986/the-type-java-lang-charsequence-cannot-be-resolved-in-package-declaration) is saying that some methods are incompatible between Java 7 and 8, and that I should fully commit to one or the other.  Is there some way to set Java 8 and/or determine the offending dependency(s)?

(btw I'm having trouble posting to the mailing list, so I'm trying here instead).

**Comment by qsiebers** [comment]
>  I am hitting some roadblocks when running it

Are you running it from the generated distribution tomcat, or in your own tomcat? If your own: what version of tomcat are you using.

What version of java are you using? Is tomcat correctly using the java version you expect it to use?

I've tried a clean distribution build and ran into some problems related to java 8 / tomcat 7 use. Could you tell me what problems you ran into and how you addressed those? 

I think the errors you are seeing now are a result of some compatibility issues between java and tomcat versions, that might not be directly code related, because:

```
The type java.util.Map$Entry cannot be resolved.
```
This class exists in java 6, 7, 8 and even 9. Meaning it can never not be found unless something is going very wrong.

**Comment by achea** [comment]
Ok, the page itself says `note The full stack trace of the root cause is available in the Apache Tomcat/7.0.10 logs.` and I don't have tomcat installed, so maybe 7.0.10 is bundled in/pulled by ontopia?  I only have Oracle JDK 1.8.0.162, as JDK 7 was purged from my upstream repos.

I did run into doclint and tests failures, and as a temporary workaround disabled those, but in the long term they should be fixed though - I just wanted to see if I could get it running first. :)  Which it does for the most part: I can create and edit topics in Ontopoly, see some of Omnigator, but don't have java applet support to test the visualizer.

 * Command I used to build: `mvn clean install -DskipTests -Pontopia-distribution-tomcat`
 * Upgraded to Maven 3.3.9 because of a bug with parsing a comma from String to List in the catalina patches.

https://stackoverflow.com/questions/15886209/maven-is-not-working-in-java-8-when-javadoc-tags-are-incomplete#16743137
```
diff --git a/pom.xml b/pom.xml
index bd7d5521..12acba20 100644
--- a/pom.xml
+++ b/pom.xml
@@ -670,6 +670,15 @@
                                </plugins>
                        </build>
                </profile>
+               <profile>
+                       <id>java8-doclint-disabled</id>
+                       <activation>
+                               <jdk>[1.8,)</jdk>
+                       </activation>
+                       <properties>
+                               <javadoc.opts>-Xdoclint:none</javadoc.opts>
+                       </properties>
+               </profile>
                <profile>
                        <!-- Profile used for making the tomcat distribution -->
                        <id>ontopia-distribution-tomcat</id>
@@ -685,6 +694,9 @@
                                                                <goals>
                                                                        <goal>aggregate</goal>
                                                                </goals>
+                                                               <configuration>
+                                                                       <additionalparam>${javadoc.opts}</additionalparam>
+                                                               </configuration>
                                                        </execution>
                                                </executions>
                                                <configuration>
```

To test a newer tomcat, which files/lines do I edit to bump its version?

**Comment by qsiebers** [comment]
> I only have Oracle JDK 1.8.0.162, as JDK 7 was purged from my upstream repos.

That I guess it should be safe to assume tomcat is indeed running java 8. 

> Command I used to build: mvn clean install -DskipTests -Pontopia-distribution-tomcat

Good, that should indeed lead to a bundled tomcat 7.0.10.

> Upgraded to Maven 3.3.9 because of a bug with parsing a comma from String to List in the catalina patches.

I haven't encountered those issues before, but I'm already on maven 3.5.0. Good to see you managed to get past the patching issues.

> Javadoc issues with java 8

I've come across those as well, and those should either be fixed, or ignored. I've applied a slightly smaller fix/workaround:
```
<failOnError>false</failOnError>
```

I've run into different errors when using tomcat 7.0.10, have you encountered these?
```
org.apache.tomcat.util.bcel.classfile.ClassFormatException: Invalid byte tag in constant pool: 15
```

I've fixed these by upgrading to tomcat 7.0.85 by changing the `ontopia-distribution-tomcat/pom.xml`: 
```
<tomcat.version>7.0.85</tomcat.version>
```

After all that, my Ontopia is working as expected. I've tried some of the default topicmaps but haven't been able to reproduce the errors you are getting. Can you try if a newer tomcat version fixes your issues?

**Comment by achea** [comment]
Yes, thanks!  Bumping the tomcat version to 7.0.85 lets me access the "Customize" and "Filter" options now!  I didn't get your `ClassFormatException` though, maybe because I had failed earlier with my above errors?  In any case, the version bump looks to be the way to go.

**Comment by qsiebers** [comment]
Fixed javadoc issue in b49e07ed4a461d2d605037155497a81cc0e48530

**Comment by qsiebers** [comment]
Set compiler version to 1.8 in c2f34a425ceddec22fd6afd1c79d06543853a65f

**Comment by qsiebers** [comment]
Automated building set to java 8 in e200e7b326286096ec2f03f40eba62799924b763
