### ISSUE TITLE
Reason for deletion of CompactHashMap?

### ISSUE THREAD

**Issue by stefan-reich** [ontopia/ontopia#542]
Hi,

I already praised your CompactHashSet, now I'm on to CompactHashMap... [It used to exist](https://searchcode.com/codesearch/view/12810879/), now it is no longer part of the GitHub repository. Just curious why :)

Many greetings & happy new year!
Stefan

**Comment by qsiebers** [comment]
It was removed in 1bec71ac47e736dc9cf18fdb1ead88227aa17deb, because it was no longer used. As for why it was no longer use, I don't know. You would have to dig through the history to find out when it was last used.

**Comment by stefan-reich** [comment]
Thanks! I have used the old version and adapted it to my needs.
